### ISSUE TITLE
Use `bluesky.abc.Readable` to identify devices in Run Engine Workspace

### ISSUE THREAD

**Issue by dmgav** [bluesky/bluesky-queueserver#162]
Currently the list of devices (detectors, motors, etc.) is generated by finding all objects in the namespace that are inherited from `ophyd.ophydobj.OphydObject`. The disadvantages of this approach:

- Works only with Ophyd objects.

- Requires importing `ophyd` (which is importing `pyepics`).

Current implementation of the function collecting devices from the workspace: https://github.com/bluesky/bluesky-queueserver/blob/5e59302c98b2435c2101868768dc1f69178ec426/bluesky_queueserver/manager/profile_ops.py#L447

The proposed change includes replacing the code 
```
       if isinstance(obj, ophyd.ophydobj.OphydObject):
```    
with
```
        if isinstance(obj, bluesky.abc.Readable):
```  
This will allow to detect all items with types inherited from `ophyd.Device` and `ophyd.Signal` without importing `ophyd`.

The class `bluesky.abc.Readable` is currently not part of Bluesky. The change may be implemented only after the PR https://github.com/bluesky/bluesky/pull/1446 is merged.

**Comment by dmgav** [comment]
@danielballan @tacaswell What do we need to do before we can merge https://github.com/bluesky/bluesky/pull/1446?

**Comment by danielballan** [comment]
I’ll try to review it in detail today.

**Comment by ksunden** [comment]
https://github.com/bluesky/bluesky-queueserver/compare/main...ksunden:yaqc_bluesky?expand=1

For what its worth, I have a branch with this change implemented, and it has worked in my testing with non-ophyd devices (yaqc-bluesky)

I also needed to add in the Flyer interface class, since flyers are not (necessarily) Readable devices (and in fact the sim flyers in ophyd are _not_ compliant to the readable interface)

I think it may have been fixed by #160, but when I first did the test branch some tests failed due to additional items in the namespace that fit the Readable interface without being inherited from the ophyd class.

**Comment by danielballan** [comment]
The protocols PR is now merged but not yet released. @ksunden Was there more you wanted to do with Flyers before we release it? I’m fine with making incremental improvements after the release…up to you.

**Comment by ksunden** [comment]
I do not have any concrete thing to do about Flyers, I do not at present use them anywhere or have concrete plans to in the near term. I think @thomascobb had indicated that he had some ideas, and has done more actual thought on the matter

**Comment by dmgav** [comment]
Addressed in https://github.com/bluesky/bluesky-queueserver/pull/163
